spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/payment_service
    username: postgres
    password: 123456
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8083
vnpay:
  tmn-code: ${VNP_TMN_CODE}
  hash-secret: ${VNP_SECRET_KEY}
  url: ${VNP_PAYMENT_URL}
  return-url: ${VNP_RETURN_URL}
  api-url: ${VNP_API_URL:https://sandbox.vnpayment.vn/merchant_webapi/api/transaction}

logging:
  level:
    com.sgu.payment_service.utils.VNPayUtil: DEBUG
    com.sgu.payment_service.service.impl.VNPayServiceImpl: DEBUG
user-service:
  url: http://localhost:8082  # Port cá»§a User Service